# Minimal Theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: brittni and the polar bear | twitch stream notes
description: notes about resources and music from twitch streams by brittni and the polar bear.
logo: "https://brittni-and-the-polar-bear.github.io/assets/img/logo.png"
show_downloads: false
